export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_NEW_GAME_SUCCESS = 'LOAD_NEW_GAME_SUCCESS';
export const SHUFFLE_DECKS_SUCCESS = 'SHUFFLE_DECKS_SUCCESS';

export const LOAD_HIGH_SCORES_SUCCESS = 'LOAD_HIGH_SCORES_SUCCESS';
export const END_GAME_SUCCESS = 'END_GAME_SUCCESS';
export const RESET_SCORES_SUCCESS = 'RESET_SCORES_SUCCESS';

export const REVEAL_CARD = 'REVEAL_CARD';